/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufu.facom.persim.view;

import br.ufu.facom.persim.control.TrabalhosControl;
import br.ufu.facom.persim.control.ReunioesControl;
import br.ufu.facom.persim.control.EventosControl;
import br.ufu.facom.persim.control.ControleDisciplinaControl;
import br.ufu.facom.persim.model.Trabalhos;
import br.ufu.facom.persim.model.Reunioes;
import br.ufu.facom.persim.model.Eventos;
import br.ufu.facom.persim.model.ControleDisciplina;
import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ricardo & Ludma
 */
public class GerenciamentoAtividadesAcademicas extends javax.swing.JInternalFrame {

    int linhas1=0, linhas2=0, linhas3=0, linhaTabela;
    String descricaoTrabalho, descricaoReuniao, dataTrabalho, dataReuniao, evento, diaEvento, horaEvento, minutoEvento, hEvento;
    List<String> trabalhos;
    List<String> reunioes;
    /**
     * Creates new form GerenciamentoAtividadesAcademicas
     */
    public GerenciamentoAtividadesAcademicas() {
        initComponents();
        recuperaTBTrabalho();  
        recuperaTBEvento();
        recuperaTBReuniao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JScrollPane();
        txtDescTrabalho = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        dtEntregaTrabalho = new javax.swing.JFormattedTextField();
        addEntregaTrabalho = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEntregaTrabalho = new javax.swing.JTable();
        removeTrabalho = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDescricao1 = new javax.swing.JScrollPane();
        txtDescReuniao = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        dtReuniao = new javax.swing.JFormattedTextField();
        addReuniao = new javax.swing.JButton();
        removeReuniao = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbReuniao = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        controleDisciplina = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtEvento = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbEventos = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        horas = new javax.swing.JSpinner();
        minutos = new javax.swing.JSpinner();
        addEvento = new javax.swing.JButton();
        rmvEvento = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Entrega");

        jLabel2.setText("Descrição:");

        txtDescTrabalho.setColumns(20);
        txtDescTrabalho.setRows(5);
        txtDescricao.setViewportView(txtDescTrabalho);

        jLabel3.setText("Data:");

        try {
            dtEntregaTrabalho.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        addEntregaTrabalho.setText("Adicionar Evento");
        addEntregaTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEntregaTrabalhoActionPerformed(evt);
            }
        });

        tbEntregaTrabalho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Data Entrega"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbEntregaTrabalho);
        tbEntregaTrabalho.getColumnModel().getColumn(0).setMinWidth(220);
        tbEntregaTrabalho.getColumnModel().getColumn(0).setMaxWidth(220);

        removeTrabalho.setText("Remover Evento");
        removeTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTrabalhoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Reuniões");

        jLabel5.setText("Descrição:");

        txtDescReuniao.setColumns(20);
        txtDescReuniao.setRows(5);
        txtDescricao1.setViewportView(txtDescReuniao);

        jLabel6.setText("Data:");

        try {
            dtReuniao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        addReuniao.setText("Adicionar Evento");
        addReuniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReuniaoActionPerformed(evt);
            }
        });

        removeReuniao.setText("Remover Evento");
        removeReuniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeReuniaoActionPerformed(evt);
            }
        });

        tbReuniao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Data Entrega"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbReuniao);
        tbReuniao.getColumnModel().getColumn(0).setMinWidth(220);
        tbReuniao.getColumnModel().getColumn(0).setMaxWidth(220);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtEntregaTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addEntregaTrabalho)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeTrabalho))
                    .addComponent(txtDescricao, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dtReuniao, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(addReuniao)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(removeReuniao))
                        .addComponent(txtDescricao1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dtEntregaTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addEntregaTrabalho)
                            .addComponent(removeTrabalho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(dtReuniao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addReuniao)
                            .addComponent(removeReuniao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trabalhos", jPanel1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Provas:");

        controleDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Disciplina", "Notas", "Faltas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(controleDisciplina);
        controleDisciplina.getColumnModel().getColumn(0).setResizable(false);
        controleDisciplina.getColumnModel().getColumn(1).setResizable(false);
        controleDisciplina.getColumnModel().getColumn(2).setResizable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Provas", jPanel2);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Descrição/Data/Hora do evento:");

        jLabel9.setText("Descrição:");

        txtEvento.setColumns(20);
        txtEvento.setRows(5);
        jScrollPane4.setViewportView(txtEvento);

        tbEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Data", "Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tbEventos);
        tbEventos.getColumnModel().getColumn(0).setResizable(false);
        tbEventos.getColumnModel().getColumn(0).setPreferredWidth(300);
        tbEventos.getColumnModel().getColumn(1).setResizable(false);
        tbEventos.getColumnModel().getColumn(2).setResizable(false);

        jLabel10.setText("Data:");

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setText("Horário:");

        horas.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        horas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        minutos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        addEvento.setText("Adicionar Evento");
        addEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEventoActionPerformed(evt);
            }
        });

        rmvEvento.setText("Remover Evento");
        rmvEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmvEventoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane4)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(horas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(minutos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(addEvento)
                        .addGap(18, 18, 18)
                        .addComponent(rmvEvento)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addEvento)
                            .addComponent(rmvEvento))
                        .addGap(53, 53, 53))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Extra Curriculares", jPanel3);

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelar)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEntregaTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEntregaTrabalhoActionPerformed
        gravarTBTrabalho();
    }//GEN-LAST:event_addEntregaTrabalhoActionPerformed

    private void removeTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTrabalhoActionPerformed
        removeTBTrabalho();
    }//GEN-LAST:event_removeTrabalhoActionPerformed

    private void addReuniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReuniaoActionPerformed
        gravarTBReuniao();
    }//GEN-LAST:event_addReuniaoActionPerformed

    private void removeReuniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeReuniaoActionPerformed
        removeTBReuniao();
    }//GEN-LAST:event_removeReuniaoActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GerenciamentoAtividadesAcademicas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelarActionPerformed

    private void addEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEventoActionPerformed
        gravarTBEvento();
    }//GEN-LAST:event_addEventoActionPerformed

    private void rmvEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmvEventoActionPerformed
        removeTBEvento();
    }//GEN-LAST:event_rmvEventoActionPerformed
        
    public void tbEvento(String descricao, String dia, String hora)
    {
        DefaultTableModel modelo = (DefaultTableModel) tbEventos.getModel();
        modelo.setNumRows(linhas3);
        modelo.addRow(new Object[]{descricao,dia,hora});
        linhas3++;
    }
    
    public void removerEvento(int linha)
    {
        DefaultTableModel modelo = (DefaultTableModel) tbEventos.getModel();
        modelo.removeRow(linha);
        linhas3--;
    }
    
    public void gravarTBEvento()
    {
        evento = txtEvento.getText().toString();
        diaEvento = txtData.getText().toString();
        horaEvento = horas.getValue().toString();
        minutoEvento = minutos.getValue().toString();
        tbEvento(evento, diaEvento, horaEvento+":"+minutoEvento);
        Eventos even = new Eventos(descricaoTrabalho, diaEvento, horaEvento+":"+minutoEvento);
        EventosControl.save(even);
    }
    
    public void recuperaTBEvento()
    {
        Eventos even = EventosControl.load();
        DefaultTableModel modelo = (DefaultTableModel) tbEventos.getModel();
        modelo.addRow(new Object[]{even.getDecricao(),even.getDia(),even.getHora()});
        
    }
    
    public void removeTBEvento()
    {
        DefaultTableModel modelo = (DefaultTableModel) tbEventos.getModel();
        linhaTabela = tbEventos.getSelectedRow();       
        evento = modelo.getValueAt(linhaTabela, 0).toString();
        diaEvento = modelo.getValueAt(linhaTabela, 1).toString();
        hEvento = modelo.getValueAt(linhaTabela, 2).toString();
        EventosControl.remove(descricaoTrabalho, dataTrabalho, hEvento);
        removerEvento(linhaTabela);
    }
    
    public void recuperaControleDisciplina()
    {
        ControleDisciplina control = ControleDisciplinaControl.load();
        DefaultTableModel modelo = (DefaultTableModel) controleDisciplina.getModel();
        modelo.addRow(new Object[]{control.getDisc_id(),control.getNotas(),control.getFaltas()});
    }
    
    public void tbTrabalho(String descricao, String dia) {
        //Conexao.conectar();        
        DefaultTableModel modelo = (DefaultTableModel) tbEntregaTrabalho.getModel();
        modelo.setNumRows(linhas1);
        modelo.addRow(new Object[]{descricao,dia});
        linhas1++;
    }
    
    public void removerTrabalho(int linha){
        DefaultTableModel modelo = (DefaultTableModel) tbEntregaTrabalho.getModel();
        modelo.removeRow(linha);
        linhas1--;
    }
    
    public void gravarTBTrabalho()
    {
        dataTrabalho = dtEntregaTrabalho.getText().toString();
        descricaoTrabalho = txtDescTrabalho.getText().toString();
        System.out.println("DescTrabalho "+descricaoTrabalho);
        tbTrabalho(descricaoTrabalho, dataTrabalho);
        Trabalhos trab = new Trabalhos(descricaoTrabalho, dataTrabalho);
        TrabalhosControl.save(trab);
    }
    
    public void recuperaTBTrabalho()
    {
        Trabalhos trab = TrabalhosControl.load();
        DefaultTableModel modelo = (DefaultTableModel) tbEntregaTrabalho.getModel();
        modelo.addRow(new Object[]{trab.getDecricao(),trab.getDia()});
        
    }
    
    public void removeTBTrabalho()
    {
        DefaultTableModel modelo = (DefaultTableModel) tbEntregaTrabalho.getModel();
        linhaTabela = tbEntregaTrabalho.getSelectedRow();       
        descricaoTrabalho = modelo.getValueAt(linhaTabela, 0).toString();
        dataTrabalho = modelo.getValueAt(linhaTabela, 1).toString();
        TrabalhosControl.remove(descricaoTrabalho, dataTrabalho);
        removerTrabalho(linhaTabela);
    }
    
    public void tableReuniao(String descricao, String dia) {
        //Conexao.conectar();        
        DefaultTableModel modelo = (DefaultTableModel) tbReuniao.getModel();
        modelo.setNumRows(linhas2);
        modelo.addRow(new Object[]{descricao,dia});
        linhas2++;
    }
    
    public void removerReuniao(int linha){
        DefaultTableModel modelo = (DefaultTableModel) tbReuniao.getModel();
        modelo.removeRow(linha);
        linhas2--;
    }
    
    public void gravarTBReuniao()
    {
        dataReuniao = dtReuniao.getText().toString();
        descricaoReuniao = txtDescReuniao.getText().toString();
        System.out.println("DescTrabalho "+descricaoReuniao);
        tableReuniao(descricaoReuniao, dataReuniao);
        Reunioes reun = new Reunioes(descricaoReuniao, dataReuniao);
        ReunioesControl.save(reun);
    }
    
    public void recuperaTBReuniao()
    {
        Reunioes reun = ReunioesControl.load();
        DefaultTableModel modelo = (DefaultTableModel) tbReuniao.getModel();
        modelo.addRow(new Object[]{reun.getDecricao(),reun.getDia()});        
    }
    
    public void removeTBReuniao()
    {
        DefaultTableModel modelo = (DefaultTableModel) tbReuniao.getModel();
        linhaTabela = tbReuniao.getSelectedRow();       
        descricaoReuniao = modelo.getValueAt(linhaTabela, 0).toString();
        dataReuniao = modelo.getValueAt(linhaTabela, 1).toString();
        ReunioesControl.remove(descricaoReuniao, dataReuniao);
        removerReuniao(linhaTabela);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEntregaTrabalho;
    private javax.swing.JButton addEvento;
    private javax.swing.JButton addReuniao;
    private javax.swing.JButton cancelar;
    private javax.swing.JTable controleDisciplina;
    private javax.swing.JFormattedTextField dtEntregaTrabalho;
    private javax.swing.JFormattedTextField dtReuniao;
    private javax.swing.JSpinner horas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner minutos;
    private javax.swing.JButton removeReuniao;
    private javax.swing.JButton removeTrabalho;
    private javax.swing.JButton rmvEvento;
    private javax.swing.JTable tbEntregaTrabalho;
    private javax.swing.JTable tbEventos;
    private javax.swing.JTable tbReuniao;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextArea txtDescReuniao;
    private javax.swing.JTextArea txtDescTrabalho;
    private javax.swing.JScrollPane txtDescricao;
    private javax.swing.JScrollPane txtDescricao1;
    private javax.swing.JTextArea txtEvento;
    // End of variables declaration//GEN-END:variables
}
